# ============================================================
# Telecom Order Orchestration - Full Backstage Catalog File
# ============================================================

# ---- Domain ----
apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: telecom
  title: Telecom Domain
  description: >
    Domain representing telecom OSS/BSS systems — including CRM, Billing, and Order Orchestration.
spec:
  owner: group:team-order-ops
---
# ---- Team ----
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: team-order-ops
  title: Team Order Ops
  description: >
    Team responsible for developing and maintaining telecom order orchestration microservices.
spec:
  type: team
  profile:
    displayName: Order Operations
    email: orderops@telco.org
  children: []
---
# ---- System ----
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: order-orchestration-system
  title: Order Orchestration System
  description: >
    System that manages the complete telecom order lifecycle across CRM, Billing, and Provisioning layers.
  tags:
    - telecom
    - orchestration
spec:
  owner: group:team-order-ops
  domain: telecom
---
# ---- Resource: Order Database ----
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: order-db
  title: Order Database
  description: PostgreSQL database for order management and tracking.
spec:
  type: database
  owner: group:team-order-ops
  system: order-orchestration-system
---
# ---- Resource: Kafka Topic ----
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: order-events-topic
  title: Order Events Topic
  description: Kafka topic used for publishing and consuming order lifecycle events.
spec:
  type: messaging-topic
  owner: group:team-order-ops
  system: order-orchestration-system
---
# ---- Component: Order Service ----
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: order-service
  title: Order Service
  description: >
    Core microservice orchestrating telecom customer orders across CRM, Billing,
    and Provisioning systems. Provides REST and event-driven APIs.
  tags:
    - telecom
    - microservice
    - orders
    - orchestration
  annotations:
    github.com/project-slug: telco-org/order-service
    backstage.io/techdocs-ref: dir:.
    backstage.io/kubernetes-id: order-service
    backstage.io/kubernetes-namespace: telco-prod
    grafana/dashboard-url: https://grafana.telco.org/d/order-service
    pagerduty.com/service-id: P123456
spec:
  type: service
  lifecycle: production
  owner: group:team-order-ops
  system: order-orchestration-system
  providesApis:
    - order-api
    - order-events-api
  consumesApis:
    - billing-api
    - provisioning-api
    - notification-api
  dependsOn:
    - resource:order-db
    - resource:order-events-topic
  links:
    - url: https://github.com/telco-org/order-service
      title: GitHub Repository
      icon: github
    - url: https://grafana.telco.org/d/order-service
      title: Grafana Dashboard
      icon: grafana
    - url: https://argocd.telco.org/applications/order-service
      title: ArgoCD Deployment
      icon: kubernetes
    - url: https://pagerduty.com/services/P123456
      title: PagerDuty Alerts
      icon: pagerduty
---
# ---- REST API: Order API ----
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: order-api
  title: Order API
  description: >
    REST API for creating, retrieving, and managing telecom orders.
  tags:
    - rest
    - orders
spec:
  type: openapi
  lifecycle: production
  owner: group:team-order-ops
  system: order-orchestration-system
  definition:
    $text: |
      openapi: 3.0.1
      info:
        title: Order API
        version: 1.0.0
      paths:
        /orders:
          post:
            summary: Create a new order
            requestBody:
              required: true
              content:
                application/json:
                  schema:
                    type: object
                    properties:
                      customerId:
                        type: string
                      productCode:
                        type: string
                      quantity:
                        type: integer
            responses:
              "201":
                description: Order created successfully
          get:
            summary: Retrieve all orders
            responses:
              "200":
                description: Success
        /orders/{orderId}:
          get:
            summary: Retrieve order by ID
            parameters:
              - name: orderId
                in: path
                required: true
                schema:
                  type: string
            responses:
              "200":
                description: Success
---
# ---- Async API: Order Events ----
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: order-events-api
  title: Order Events API
  description: >
    Kafka topics used to broadcast order lifecycle events such as order creation, completion, and cancellation.
  tags:
    - async
    - kafka
spec:
  type: asyncapi
  lifecycle: production
  owner: group:team-order-ops
  system: order-orchestration-system
  definition:
    $text: |
      asyncapi: 2.5.0
      info:
        title: Order Events API
        version: 1.0.0
      servers:
        kafkaServer:
          url: kafka.telco.org:9092
          protocol: kafka
      channels:
        order.created:
          publish:
            message:
              name: OrderCreated
              payload:
                type: object
                properties:
                  orderId:
                    type: string
                  createdAt:
                    type: string
                    format: date-time
        order.completed:
          publish:
            message:
              name: OrderCompleted
              payload:
                type: object
                properties:
                  orderId:
                    type: string
                  completedAt:
                    type: string
                    format: date-time
        order.cancelled:
          publish:
            message:
              name: OrderCancelled
              payload:
                type: object
                properties:
                  orderId:
                    type: string
                  reason:
                    type: string
---
# ---- External API: Billing ----
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: billing-api
  title: Billing API
  description: External API used for validating and charging telecom orders.
spec:
  type: openapi
  lifecycle: production
  owner: group:team-billing
  definition:
    $text: |
      openapi: 3.0.1
      info:
        title: Billing API
        version: 1.0.0
      paths:
        /billing/validate:
          post:
            summary: Validate billing for an order
            responses:
              "200":
                description: Validation success
---
# ---- External API: Provisioning ----
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: provisioning-api
  title: Provisioning API
  description: API for activating telecom services after order fulfillment.
spec:
  type: openapi
  lifecycle: production
  owner: group:team-provisioning
  definition:
    $text: |
      openapi: 3.0.1
      info:
        title: Provisioning API
        version: 1.0.0
      paths:
        /provision/activate:
          post:
            summary: Activate customer service
            responses:
              "200":
                description: Activated
---
# ---- External API: Notification ----
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: notification-api
  title: Notification API
  description: API for sending customer notifications via SMS and email.
spec:
  type: openapi
  lifecycle: production
  owner: group:team-notifications
  definition:
    $text: |
      openapi: 3.0.1
      info:
        title: Notification API
        version: 1.0.0
      paths:
        /notify:
          post:
            summary: Send a notification to a customer
            requestBody:
              required: true
              content:
                application/json:
                  schema:
                    type: object
                    properties:
                      message:
                        type: string
                      recipient:
                        type: string
            responses:
              "200":
                description: Notification sent successfully
