# ============================================================
# Backstage Catalog - Telecom Order Orchestration (Validated)
# ============================================================

# ---- Domain ----
apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: telecom
  title: Telecom Domain
  description: >
    Domain for telecom OSS/BSS order management and orchestration systems.
spec:
  owner: group:team-order-ops
---
# ---- Team (Group) ----
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: team-order-ops
  title: Team Order Ops
  description: >
    Team responsible for telecom order orchestration, provisioning, and integrations.
spec:
  type: team
  profile:
    displayName: Order Operations
    email: orderops@telco.org
  children: []
---
# ---- System ----
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: order-orchestration-system
  title: Order Orchestration System
  description: >
    Manages customer order lifecycle across CRM, Billing, and Provisioning systems.
  tags:
    - telecom
    - orchestration
spec:
  owner: group:team-order-ops
  domain: telecom
---
# ---- Resource: Database ----
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: order-db
  title: Order Database
  description: PostgreSQL database for storing order information.
spec:
  type: database
  owner: group:team-order-ops
  system: order-orchestration-system
---
# ---- Resource: Kafka Topic ----
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: order-events-topic
  title: Order Events Topic
  description: Kafka topic for publishing order lifecycle events.
spec:
  type: messaging-topic
  owner: group:team-order-ops
  system: order-orchestration-system
---
# ---- Component: Order Service ----
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: order-service
  title: Order Service
  description: >
    Microservice that orchestrates telecom customer orders across CRM, Billing,
    and Provisioning systems. Exposes REST and event-based APIs.
  tags:
    - telecom
    - microservice
    - orders
    - orchestration
  annotations:
    github.com/project-slug: telco-org/order-service
    backstage.io/techdocs-ref: dir:.
    backstage.io/kubernetes-id: order-service
    backstage.io/kubernetes-namespace: telco-prod
    grafana/dashboard-url: https://grafana.telco.org/d/order-service
    pagerduty.com/service-id: P123456
spec:
  type: service
  lifecycle: production
  owner: group:team-order-ops
  system: order-orchestration-system
  providesApis:
    - order-api
    - order-events-api
  consumesApis:
    - billing-api
    - provisioning-api
    - notification-api
  dependsOn:
    - resource:order-db
    - resource:order-events-topic
  links:
    - url: https://github.com/telco-org/order-service
      title: GitHub Repository
      icon: github
    - url: https://grafana.telco.org/d/order-service
      title: Grafana Dashboard
      icon: grafana
    - url: https://argocd.telco.org/applications/order-service
      title: ArgoCD Deployment
      icon: kubernetes
    - url: https://pagerduty.com/services/P123456
      title: PagerDuty Alerts
      icon: pagerduty
---
# ---- REST API: Order API ----
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: order-api
  title: Order API
  description: REST API for creating, retrieving, and managing telecom orders.
  tags:
    - rest
    - orders
spec:
  type: openapi
  lifecycle: production
  owner: group:team-order-ops
  system: order-orchestration-system
  definition:
    $text: |
      openapi: 3.0.1
      info:
        title: Order API
        version: 1.0.0
      paths:
        /orders:
          post:
            summary: Create a new order
            requestBody:
              required: true
              content:
                application/json:
                  schema:
                    type: object
                    properties:
                      customerId:
                        type: string
                      productCode:
                        type: string
                      quantity:
                        type: integer
            responses:
              "201":
                description: Order created successfully
          get:
            summary: Retrieve all orders
            responses:
              "200":
                description: Success
        /orders/{orderId}:
          get:
            summary: Retrieve order by ID
            parameters:
              - name: orderId
                in: path
                required: true
                schema:
                  type: string
            responses:
              "200":
                description: Success
---
# ---- Async API: Order Events ----
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: order-events-api
  title: Order Events API
  description: Kafka topics used to publish order lifecycle events.
  tags:
    - async
    - kafka
spec:
  type: asyncapi
  lifecycle: production
  owner: group:team-order-ops
  system: order-orchestration-system
  definition:
    $text: |
      asyncapi: 2.5.0
      info:
        title: Order Events API
        version: 1.0.0
      servers:
        kafkaServer:
          url: kafka.telco.org:9092
          protocol: kafka
      channels:
        order.created:
          publish:
            message:
              name: OrderCreated
              payload:
                type: object
                properties:
                  orderId:
                    type: string
                  createdAt:
                    type: string
        order.completed:
          publish:
            message:
              name: OrderCompleted
              payload:
                type: object
                properties:
                  orderId:
                    type: string
                  completedAt:
                    type: string
---
# ---- External API: Billing ----
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: billing-api
  title: Billing API
  description: External API used for validating order charges and payments.
spec:
  type: openapi
  lifecycle: production
  owner: group:team-billing
  definition:
    $text: |
      openapi: 3.0.1
      info:
        title: Billing API
        version: 1.0.0
      paths: {}
---
# ---- External API: Provisioning ----
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: provisioning-api
  title: Provisioning API
  description: API for activating telecom services after order fulfillment.
spec:
  type: openapi
  lifecycle: production
  owner: group:team-provisioning
  definition:
    $text: |
      openapi: 3.0.1
      info:
        title: Provisioning API
        version: 1.0.0
      paths: {}
---
# ---- External API: Notification ----
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: notification-api
  title: Notification API
  description: API for sending customer notifications (SMS/Email).
spec:
  type: openapi
  lifecycle: production
  owner: group:team-notifications
  definition:
    $text: |
      openapi: 3.0.1
      info:
        title: Notification API
        version: 1.0.0
      paths: {}
