# =========================================================
# Backstage Catalog - Telecom Order Orchestration Example
# =========================================================

# ---- Domain ----
apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: telecom
  title: Telecom Domain
  description: >
    The telecom OSS/BSS domain handling CRM, Billing, and Order orchestration services.
spec:
  owner: team-order-ops
---
# ---- Team (Group / Owner) ----
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: team-order-ops
  title: Team Order Ops
  description: >
    Team responsible for the telecom order orchestration platform — including
    order management, provisioning, and billing integrations.
spec:
  type: team
  profile:
    displayName: Order Operations
    email: orderops@telco.org
  children: []
---
# ---- System ----
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: order-orchestration-system
  title: Order Orchestration System
  description: >
    Central system responsible for managing customer order lifecycle across
    CRM, Billing, and Provisioning services in the telecom domain.
  tags:
    - telecom
    - orchestration
spec:
  owner: team-order-ops
  domain: telecom
---
# ---- Resources ----
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: postgres-order-db
  description: PostgreSQL database for storing order data.
spec:
  type: database
  owner: team-order-ops
  system: order-orchestration-system
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: kafka-order-topic
  description: Kafka topic for publishing order lifecycle events.
spec:
  type: messaging-topic
  owner: team-order-ops
  system: order-orchestration-system
---
# ---- Main Component ----
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: order-service
  title: Order Service
  description: >
    Microservice that orchestrates telecom customer orders across CRM, Billing,
    and Provisioning systems. Handles order creation, validation, and fulfillment.
  tags:
    - telecom
    - microservice
    - order
    - orchestration
  annotations:
    github.com/project-slug: telco-org/order-service
    backstage.io/techdocs-ref: dir:.
    backstage.io/kubernetes-id: order-service
    backstage.io/kubernetes-namespace: telco-prod
    sonarcloud.io/project-key: telco-org_order-service
    grafana/dashboard-url: https://grafana.telco.org/d/order-service
    pagerduty.com/service-id: P123456
spec:
  type: service
  lifecycle: production
  owner: team-order-ops
  system: order-orchestration-system
  providesApis:
    - order-api
    - order-events-api
  consumesApis:
    - billing-api
    - provisioning-api
    - notification-api
  dependsOn:
    - resource:postgres-order-db
    - resource:kafka-order-topic
  links:
    - url: https://github.com/telco-org/order-service
      title: GitHub Repository
      icon: github
    - url: https://telco-org.github.io/order-service/
      title: TechDocs
      icon: docs
    - url: https://grafana.telco.org/d/order-service
      title: Grafana Dashboard
      icon: grafana
    - url: https://argocd.telco.org/applications/order-service
      title: ArgoCD Deployment
      icon: kubernetes
---
# ---- REST API Definition ----
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: order-api
  title: Order API
  description: >
    REST API for creating, retrieving, and managing telecom customer orders.
  annotations:
    github.com/project-slug: telco-org/order-service
spec:
  type: openapi
  lifecycle: production
  owner: team-order-ops
  system: order-orchestration-system
  definition:
    $text: |
      openapi: 3.0.1
      info:
        title: Order API
        version: 1.0.0
      paths:
        /orders:
          post:
            summary: Create a new telecom order
            requestBody:
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/Order'
            responses:
              '201':
                description: Created
          get:
            summary: Retrieve all orders
            responses:
              '200':
                description: List of orders
        /orders/{id}:
          get:
            summary: Get details of an order by ID
            parameters:
              - name: id
                in: path
                required: true
                schema:
                  type: string
            responses:
              '200':
                description: Success
      components:
        schemas:
          Order:
            type: object
            properties:
              orderId:
                type: string
              customerId:
                type: string
              productCode:
                type: string
              status:
                type: string
---
# ---- Async API Definition (Kafka) ----
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: order-events-api
  title: Order Events API
  description: >
    Kafka events published by the Order Service for order lifecycle changes.
spec:
  type: asyncapi
  lifecycle: production
  owner: team-order-ops
  system: order-orchestration-system
  definition:
    $text: |
      asyncapi: 2.5.0
      info:
        title: Order Events API
        version: 1.0.0
      servers:
        prod:
          url: kafka.telco.org:9092
          protocol: kafka
      channels:
        order.created:
          publish:
            message:
              name: OrderCreated
              payload:
                type: object
                properties:
                  orderId:
                    type: string
                  createdAt:
                    type: string
        order.completed:
          publish:
            message:
              name: OrderCompleted
              payload:
                type: object
                properties:
                  orderId:
                    type: string
                  completedAt:
                    type: string
---
# ---- External APIs Consumed ----
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: billing-api
  description: External billing API for validating charges and payments.
spec:
  type: openapi
  lifecycle: production
  owner: team-billing
  definition:
    $text: |
      openapi: 3.0.1
      info:
        title: Billing API
        version: 1.0.0
      paths: {}
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: provisioning-api
  description: External provisioning API for activating telecom services.
spec:
  type: openapi
  lifecycle: production
  owner: team-provisioning
  definition:
    $text: |
      openapi: 3.0.1
      info:
        title: Provisioning API
        version: 1.0.0
      paths: {}
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: notification-api
  description: External API for sending SMS/email notifications.
spec:
  type: openapi
  lifecycle: production
  owner: team-notifications
  definition:
    $text: |
      openapi: 3.0.1
      info:
        title: Notification API
        version: 1.0.0
      paths: {}
